# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: global_controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'global_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17global_controller.proto\x12\x11global_controller\"\x1f\n\x0cJsonResponse\x12\x0f\n\x07resonse\x18\x01 \x01(\t2a\n\x10GlobalController\x12M\n\x07\x45xecute\x12\x1f.global_controller.JsonResponse\x1a\x1f.global_controller.JsonResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'global_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONRESPONSE']._serialized_start=46
  _globals['_JSONRESPONSE']._serialized_end=77
  _globals['_GLOBALCONTROLLER']._serialized_start=79
  _globals['_GLOBALCONTROLLER']._serialized_end=176
# @@protoc_insertion_point(module_scope)
